/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IAvatarPicker: typeof import('./src/components/IAvatarPicker.vue')['default']
    IAvatarUploadToolbar: typeof import('./src/components/IAvatarUploadToolbar.vue')['default']
    IChipWord: typeof import('./src/components/IChipWord.vue')['default']
    IConfirmDialog: typeof import('./src/components/IConfirmDialog.vue')['default']
    IMessage: typeof import('./src/components/IMessage.vue')['default']
    IPinCodeInput: typeof import('./src/components/IPinCodeInput.vue')['default']
    IProfileForm: typeof import('./src/components/IProfileForm.vue')['default']
    IStatisticsCharts: typeof import('./src/components/IStatisticsCharts.vue')['default']
    IStatisticsPageSkeleton: typeof import('./src/components/IStatisticsPageSkeleton.vue')['default']
    IThemeToggle: typeof import('./src/components/IThemeToggle.vue')['default']
    ITranslateTask: typeof import('./src/components/ITranslateTask.vue')['default']
    IWord: typeof import('./src/components/IWord.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
