/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IConfirmDialog: typeof import('./src/components/IConfirmDialog.vue')['default']
    IPinCodeInput: typeof import('./src/components/IPinCodeInput.vue')['default']
    ITranslateTask: typeof import('./src/components/ITranslateTask.vue')['default']
    IWord: typeof import('./src/components/IWord.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
